local mod = get_mod("sneakrats")
local new_unit_templates = {
	ai_unit_gutter_runner = {
		NAME = "ai_unit_gutter_runner",
		base_template = "ai_unit_base",
		go_type = "ai_unit_with_inventory",
		husk_extensions = {
			"AiHeroicEnemyExtension",
			"AIInventoryExtension",
			"PingTargetExtension",
			"AiHuskBaseExtension",
			"AiHuskLocomotionExtension",
			"GenericHitReactionExtension",
			"GenericHealthExtension",
			"GenericDeathExtension",
			"AIProximityExtension",
			"BuffExtension",
			"ProjectileLinkerExtension",
			"EnemyOutlineExtension",
			"DialougeActorExtension",
			"AIUnitFadeExtension",
		},
		num_husk_extensions = 14,
		num_husk_extensions_server = 0,
		self_owned_extensions = {
			"AiHeroicEnemyExtension",
			"AIInventoryExtension",
			"PingTargetExtension",
			"AISimpleExtension",
			"AILocomotionExtensionC",
			"AINavigationExtension",
			"GenericHitReactionExtension",
			"GenericHealthExtension",
			"GenericDeathExtension",
			"AIProximityExtension",
			"BuffExtension",
			"ProjectileLinkerExtension",
			"EnemyOutlineExtension",
			"AIGroupMember",
			"DialougeActorExtension",
			"AIVolumeExtension",
			"AIUnitFadeExtension",
		},
		num_self_owned_extensions = 17,
		num_self_owned_extensions_server = 0,
		remove_when_killed = {
			husk_extensions = {
				"AiHuskBaseExtension",
				"AiHuskLocomotionExtension",
				"AIProximityExtension",
				"BuffExtension",
				"DialougeActorExtension",
			},
			num_husk_extensions = 5,
			self_owned_extensions = {
				"AISimpleExtension",
				"AINavigationExtension",
				"AIProximityExtension",
				"BuffExtension",
				"AIGroupMember",
				"DialougeActorExtension",
				"AIVolumeExtension",
			},
			num_self_owned_extensions = 7,
		},
	},
}
local unit_templates = require("scripts/network/unit_extension_templates")

table.merge_recursive(unit_templates, new_unit_templates)